mrpleasant@ubuntu:~$ ls
Desktop           Jupyter   NotePad++        pydb_sqlite.db  Videos
Documents         Music     Pictures         snap            VirtualBox VMs
Downloads         Mypython  Public           Templates
examples.desktop  Mytest    PycharmProjects  venv
mrpleasant@ubuntu:~$ cd PycharmProjects/
mrpleasant@ubuntu:~/PycharmProjects$ ls
Django  git_web  venv  venv_django
mrpleasant@ubuntu:~/PycharmProjects$ cd Django/
mrpleasant@ubuntu:~/PycharmProjects/Django$ ls
django_ini_remarks.txt  hardik_dj                 test.py
Django_PRAFUL           programYogeshSIrPractice
mrpleasant@ubuntu:~/PycharmProjects/Django$ cd ..
mrpleasant@ubuntu:~/PycharmProjects$ cd venv_django/
mrpleasant@ubuntu:~/PycharmProjects/venv_django$ cd venv_django/
bash: cd: venv_django/: No such file or directory
mrpleasant@ubuntu:~/PycharmProjects/venv_django$ cd ..
mrpleasant@ubuntu:~/PycharmProjects$ source venv_django/bin/activate
(venv_django) mrpleasant@ubuntu:~/PycharmProjects$ cd Django/
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django$ ls
django_ini_remarks.txt  hardik_dj                 test.py
Django_PRAFUL           programYogeshSIrPractice
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django$ cd hardik_dj/
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ ls
demo  employee
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ django adminstartproject ems
django: command not found
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ django-adminstartproject ems
django-adminstartproject: command not found
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ django-admin startproject ems
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ cd ems
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/ems$ dir
ems  manage.py
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/ems$ cd ..
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ move ems "employee management system"
No command 'move' found, did you mean:
 Command 'love' from package 'love' (universe)
 Command 'lmove' from package 'suck' (universe)
 Command 'jove' from package 'jove' (universe)
 Command 'mmove' from package 'mtools' (main)
 Command 'fmove' from package 'embassy-phylip' (multiverse)
 Command 'more' from package 'util-linux' (main)
move: command not found
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ mv ems "employee management system"
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ ls
demo  employee  employee management system
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ ce employee management system
ce: command not found
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ cd employee management system
bash: cd: too many arguments
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ cd employee management system
bash: cd: too many arguments
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ cd 
demo/                       employee management system/
employee/                   
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ cd employee
employee/                   employee management system/
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ mv employee management system "Employee_Management_System"
mv: target 'Employee_Management_System' is not a directory
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ ls
demo  employee  employee management system
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ ls
demos  employee management system
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj$ cd employee\ management\ system/
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ ls
ems  manage.py
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ dir
ems  manage.py
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python startapp employee
python: can't open file 'startapp': [Errno 2] No such file or directory
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py startapp employee
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py startapp poll
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ ls
employee  ems  manage.py  poll
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying sessions.0001_initial... OK
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py createsuperuser
Username (leave blank to use 'mrpleasant'): admin
Email address: admin@gmail.com
Password: 
Password (again): 
The password is too similar to the username.
Bypass password validation and create user anyway? [y/N]: N 
Password: 
Password (again): 
The password is too similar to the username.
This password is too short. It must contain at least 8 characters.
Bypass password validation and create user anyway? [y/N]: N
Password: 
Password (again): 
This password is too short. It must contain at least 8 characters.
This password is too common.
Bypass password validation and create user anyway? [y/N]: y
Superuser created successfully.
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py runserver
^[[1;5AWatching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
July 26, 2019 - 05:44:47
Django version 2.2.3, using settings 'ems.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[26/Jul/2019 05:45:32] "GET / HTTP/1.1" 200 16348
[26/Jul/2019 05:45:32] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[26/Jul/2019 05:45:32] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[26/Jul/2019 05:45:32] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[26/Jul/2019 05:45:32] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /favicon.ico
[26/Jul/2019 05:45:32] "GET /favicon.ico HTTP/1.1" 404 1969
[26/Jul/2019 05:46:16] "GET / HTTP/1.1" 200 16348
[26/Jul/2019 05:46:16] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[26/Jul/2019 05:46:16] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[26/Jul/2019 05:46:16] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[26/Jul/2019 05:46:16] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /favicon.ico
[26/Jul/2019 05:46:16] "GET /favicon.ico HTTP/1.1" 404 1969
Not Found: /ADMIN
[26/Jul/2019 05:46:49] "GET /ADMIN HTTP/1.1" 404 1951
[26/Jul/2019 05:47:01] "GET /admin HTTP/1.1" 301 0
[26/Jul/2019 05:47:02] "GET /admin/ HTTP/1.1" 302 0
[26/Jul/2019 05:47:02] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1819
[26/Jul/2019 05:47:02] "GET /static/admin/css/login.css HTTP/1.1" 200 1233
[26/Jul/2019 05:47:02] "GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
[26/Jul/2019 05:47:02] "GET /static/admin/css/base.css HTTP/1.1" 200 16378
[26/Jul/2019 05:47:10] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1980
[26/Jul/2019 05:47:25] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[26/Jul/2019 05:47:25] "GET /admin/ HTTP/1.1" 200 3042
[26/Jul/2019 05:47:25] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[26/Jul/2019 05:47:25] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[26/Jul/2019 05:47:25] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[26/Jul/2019 05:48:42] "GET /admin/auth/user/add/ HTTP/1.1" 200 5655
[26/Jul/2019 05:48:42] "GET /static/admin/css/forms.css HTTP/1.1" 200 8518
[26/Jul/2019 05:48:42] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[26/Jul/2019 05:48:42] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[26/Jul/2019 05:48:42] "GET /static/admin/js/core.js HTTP/1.1" 200 7099
[26/Jul/2019 05:48:42] "GET /static/admin/js/actions.js HTTP/1.1" 200 6766
[26/Jul/2019 05:48:42] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
[26/Jul/2019 05:48:42] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 271817
[26/Jul/2019 05:48:42] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
[26/Jul/2019 05:48:42] "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
[26/Jul/2019 05:48:42] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
[26/Jul/2019 05:48:42] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
[26/Jul/2019 05:48:42] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
[26/Jul/2019 05:48:42] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
[26/Jul/2019 05:49:14] "GET /admin/auth/user/ HTTP/1.1" 200 6609
[26/Jul/2019 05:49:15] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
[26/Jul/2019 05:49:15] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[26/Jul/2019 05:49:15] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[26/Jul/2019 05:49:15] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[26/Jul/2019 05:49:15] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[26/Jul/2019 05:49:15] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[26/Jul/2019 05:49:18] "GET /admin/auth/user/1/change/ HTTP/1.1" 200 13934
[26/Jul/2019 05:49:18] "GET /static/admin/js/calendar.js HTTP/1.1" 200 7777
[26/Jul/2019 05:49:18] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[26/Jul/2019 05:49:18] "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12322
[26/Jul/2019 05:49:18] "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 5753
[26/Jul/2019 05:49:18] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20218
[26/Jul/2019 05:49:18] "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
[26/Jul/2019 05:49:18] "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[26/Jul/2019 05:49:18] "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
[26/Jul/2019 05:49:18] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[26/Jul/2019 05:49:18] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[26/Jul/2019 05:56:19] "GET /admin/auth/user/ HTTP/1.1" 200 6609
[26/Jul/2019 05:56:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[26/Jul/2019 05:56:22] "GET /admin/auth/user/1/change/ HTTP/1.1" 200 13934
[26/Jul/2019 05:56:22] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[26/Jul/2019 05:56:31] "GET /admin/auth/ HTTP/1.1" 200 2968
[26/Jul/2019 05:56:33] "GET /admin/auth/group/ HTTP/1.1" 200 3502
[26/Jul/2019 05:56:33] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[26/Jul/2019 05:56:36] "GET /admin/auth/ HTTP/1.1" 200 2968
[26/Jul/2019 05:56:37] "GET /admin/auth/group/add/ HTTP/1.1" 200 6534
[26/Jul/2019 05:56:37] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[26/Jul/2019 05:57:10] "GET /admin/auth/group/ HTTP/1.1" 200 3502
[26/Jul/2019 05:57:10] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[26/Jul/2019 05:57:13] "GET /admin/auth/group/add/ HTTP/1.1" 200 6534
[26/Jul/2019 05:57:13] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[26/Jul/2019 05:58:17] "GET /admin/auth/group/ HTTP/1.1" 200 3502
[26/Jul/2019 05:58:17] "GET /admin/jsi18n/ HTTP/1.1" 200 3223
[26/Jul/2019 05:58:19] "GET /admin/auth/ HTTP/1.1" 200 2968
[26/Jul/2019 05:58:30] "GET /admin/auth/user/ HTTP/1.1" 200 6609
[26/Jul/2019 05:58:30] "GET /admin/jsi18n/ HTTP/1.1" 200 3223


^C(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee magement system$ python manage.py makemigration poll
Unknown command: 'makemigration'. Did you mean makemigrations?
Type 'manage.py help' for usage.
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py makemigration poll
Unknown command: 'makemigration'. Did you mean makemigrations?
Type 'manage.py help' for usage.
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py makemigrations poll
No installed app with label 'poll'.
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py makemigrations poll
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/mrpleasant/PycharmProjects/Django/hardik_dj/employee management system/poll/models.py", line 5, in <module>
    class Question(models.Model):
  File "/home/mrpleasant/PycharmProjects/Django/hardik_dj/employee management system/poll/models.py", line 8, in Question
    created_by = models.ForeignKey(User, null=True, blank=True)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py makemigrations poll
Migrations for 'poll':
  poll/migrations/0001_initial.py
    - Create model Question
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py migrate poll
Operations to perform:
  Apply all migrations: poll
Running migrations:
  Applying poll.0001_initial... OK
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py shell
Python 3.5.3 (default, Nov 23 2017, 11:34:05) 
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
KeyboardInterrupt
>>> 
[1]+  Stopped                 python manage.py shell
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python
Python 3.5.3 (default, Nov 23 2017, 11:34:05) 
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from poll.models import Question
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/Django/hardik_dj/employee management system/poll/models.py", line 2, in <module>
    from django.contrib.auth.models import User
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 103, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/apps/registry.py", line 134, in check_apps_ready
    settings.INSTALLED_APPS
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/conf/__init__.py", line 64, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
>>> 
[2]+  Stopped                 python
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py shell
Python 3.5.3 (default, Nov 23 2017, 11:34:05) 
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from poll.models import Question
>>> Question.objects.a
Question.objects.aggregate(    Question.objects.annotate(
Question.objects.all(          Question.objects.auto_created
>>> Question.objects.all()
<QuerySet []>
>>> 
[3]+  Stopped                 python manage.py shell
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py makemigrations poll
Migrations for 'poll':
  poll/migrations/0002_auto_20190726_0633.py
    - Add field end_date to question
    - Add field start_date to question
    - Create model Choice
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py sqlmigrate poll 0002
BEGIN;
--
-- Add field end_date to question
--
CREATE TABLE "new__poll_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "end_date" datetime NULL, "title" text NULL, "status" varchar(10) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "created_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "new__poll_question" ("updated_at", "end_date", "created_at", "status", "title", "id", "created_by_id") SELECT "updated_at", NULL, "created_at", "status", "title", "id", "created_by_id" FROM "poll_question";
DROP TABLE "poll_question";
ALTER TABLE "new__poll_question" RENAME TO "poll_question";
CREATE INDEX "poll_question_created_by_id_a39a9efb" ON "poll_question" ("created_by_id");
--
-- Add field start_date to question
--
CREATE TABLE "new__poll_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" text NULL, "status" varchar(10) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "created_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "end_date" datetime NULL, "start_date" datetime NULL);
INSERT INTO "new__poll_question" ("updated_at", "end_date", "created_at", "status", "title", "id", "created_by_id", "start_date") SELECT "updated_at", "end_date", "created_at", "status", "title", "id", "created_by_id", NULL FROM "poll_question";
DROP TABLE "poll_question";
ALTER TABLE "new__poll_question" RENAME TO "poll_question";
CREATE INDEX "poll_question_created_by_id_a39a9efb" ON "poll_question" ("created_by_id");
--
-- Create model Choice
--
CREATE TABLE "poll_choice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" text NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "question_id" integer NOT NULL REFERENCES "poll_question" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "poll_choice_question_id_bf43f391" ON "poll_choice" ("question_id");
COMMIT;
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py shell
Python 3.5.3 (default, Nov 23 2017, 11:34:05) 
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from poll.models import *
>>> q1 = Question
>>> q1 = Question()
>>> q1
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 519, in __repr__
    return '<%s: %s>' % (self.__class__.__name__, self)
TypeError: __str__ returned non-string (type NoneType)
>>> q1.title = "what is the name?"
>>> q1
<Question: what is the name?>
>>> q1.statys
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Question' object has no attribute 'statys'
>>> q1.status
'inactive'
>>> q1.save()
Traceback (most recent call last):
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table poll_question has no column named start_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table poll_question has no column named start_date
>>> q1.save()
Traceback (most recent call last):
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table poll_question has no column named start_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table poll_question has no column named start_date
>>> q1.save()
Traceback (most recent call last):
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table poll_question has no column named start_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table poll_question has no column named start_date
>>> q1.save()
Traceback (most recent call last):
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table poll_question has no column named start_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table poll_question has no column named start_date
>>> q1.title = "what is the name?"
>>> q1
<Question: what is the name?>
>>> q1.save()
Traceback (most recent call last):
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table poll_question has no column named start_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table poll_question has no column named start_date
>>> q1 = Question()
>>> q1
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 519, in __repr__
    return '<%s: %s>' % (self.__class__.__name__, self)
TypeError: __str__ returned non-string (type NoneType)
>>> q1.title = "what is the name?"
>>> q1
<Question: what is the name?>
>>> q1.status
'inactive'
>>> q1.save()
Traceback (most recent call last):
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table poll_question has no column named start_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table poll_question has no column named start_date
>>> 
[4]+  Stopped                 python manage.py shell
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py makemigrations 
No changes detected
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py migrate 
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, poll, sessions
Running migrations:
  Applying poll.0002_auto_20190726_0633... OK
(venv_django) mrpleasant@ubuntu:~/PycharmProjects/Django/hardik_dj/employee management system$ python manage.py shell
Python 3.5.3 (default, Nov 23 2017, 11:34:05) 
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from poll.models import *
>>> q1=Question()
>>> q1.title="What is your name?"
>>> q1
<Question: What is your name?>
>>> q1.save()
>>> q1.status
'inactive'
>>> Question.objects.all()
<QuerySet [<Question: What is your name?>]>
>>> Question.objects.all().count()
1
>>> q1.choice_set()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: __call__() missing 1 required keyword-only argument: 'manager'
>>> q1.choice_set.all()
<QuerySet []>
>>> c1 = choice()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'choice' is not defined
>>> c1.text = "Praful"
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'c1' is not defined
>>> q1 = choice()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'choice' is not defined
>>> q1.text = "Praful"
>>> q1
<Question: What is your name?>
>>> c1 = Choice()
>>> c1
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/base.py", line 519, in __repr__
    return '<%s: %s>' % (self.__class__.__name__, self)
TypeError: __str__ returned non-string (type NoneType)
>>> c1.text ="Praful"
>>> c1
<Choice: Praful>
>>> c1.question
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 189, in __get__
    "%s has no %s." % (self.field.model.__name__, self.field.name)
poll.models.Choice.question.RelatedObjectDoesNotExist: Choice has no question.
>>> c1.question__id = q1.id
>>> c1.question
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 189, in __get__
    "%s has no %s." % (self.field.model.__name__, self.field.name)
poll.models.Choice.question.RelatedObjectDoesNotExist: Choice has no question.
>>> c1.question = q1
>>> c1.question
<Question: What is your name?>
>>> q1.id
1
>>> c1.question_id = q1.id
>>> c1.question
<Question: What is your name?>
>>> Choice.objects.all()
<QuerySet []>
>>> c1.save()
>>> Choice.objects.all()
<QuerySet [<Choice: Praful>]>
>>> Choice.objects.all().filter
<bound method QuerySet.filter of <QuerySet [<Choice: Praful>]>>
>>> Choice.objects.all().filter(question)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'question' is not defined
>>> Choice.objects.all().filter(question__status)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'question__status' is not defined
>>> Choice.objects.all().filter(question__status='active')
<QuerySet []>
>>> Choice.objects.all().filter(question__status='inactive')
<QuerySet [<Choice: Praful>]>
>>> Choice.objects.filter(text__startwith="P", text__endwith="l")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1110, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1151, in try_transform
    "permitted%s" % (name, output_field.__name__, suggestion)
django.core.exceptions.FieldError: Unsupported lookup 'endwith' for TextField or join on the field not permitted, perhaps you meant endswith or iendswith?
>>> Choice.objects.filter(text__startwith="P", text__endswith="l")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1110, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
  File "/home/mrpleasant/PycharmProjects/venv_django/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1151, in try_transform
    "permitted%s" % (name, output_field.__name__, suggestion)
django.core.exceptions.FieldError: Unsupported lookup 'startwith' for TextField or join on the field not permitted, perhaps you meant startswith or istartswith?
>>> Choice.objects.filter(text__startswith="P", text__endswith="l")
<QuerySet [<Choice: Praful>]>

